name: unittest
description: Check the package integrity via unittest.

runs:
  using: "composite"
  steps:
    - name: Install pytest and dependencies
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        python -m pip install pytest pytest-html pytest-cov
        if [ -f tests/requirements.txt ]; then
          pip install -r tests/requirements.txt;
        fi
      shell: bash

    - name: Test with pytest
      env:
        BRANCH: ${{ github.ref_name }}
      id: pytest
      continue-on-error: true
      run: |
        python -m pytest ./tests/unittest --cov=. --cov-report xml
      shell: bash

    - name: Notice Error
      if: ${{ steps.pytest.outcome == 'failure' }}
      run: exit 1
      shell: bash
