name: validation
description: Check the package integrity via detailed validation tests.

runs:
  using: "composite"
  steps:
    - name: Install the package
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        python -m pip install --upgrade pip build
        python -m pip install .[test]
      shell: bash

    - name: Test with pytest
      env:
        BRANCH: ${{ github.ref_name }}
      id: pytest
      continue-on-error: true
      run: |
        python -m pytest ./tests --cov=. --cov-report xml
      shell: bash

    - name: Notice Error
      if: ${{ steps.pytest.outcome == 'failure' }}
      run: exit 1
      shell: bash
